### ISSUE TITLE
Cannot build r-apt codespace

### ISSUE THREAD

**Issue by grantmcdermott** [rocker-org/rocker#508]
Following up on my conversation with @eitsupi in a separate issue...

I can't seem to build a working codespaces environment from the [r-apt](https://github.com/rocker-org/devcontainer-features/tree/main/src/r-apt) feature. Here's my `.devcontainer/devontainer.json` file. The rest of my repo is empty apart from README at the top of file structure.

```sh
{
    "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
    "features": {
        "ghcr.io/rocker-org/devcontainer-features/r-apt:latest": {
            "vscodeRSupport": "full",
            "installRadian": true
        }
    }
}
```

Everything seems to be going along fine---see the full log file below---until I hit a `File has unexpected size[...] Mirror sync in progress?` error.

Am I doing something daft? Do I just need to request a bigger VM?

Many thanks in advance.

<details>
<summary><code>creation.log</code></summary>

=================================================================================
2022-11-19 22:52:12.459Z: Configuration starting...
2022-11-19 22:52:12.495Z: Cloning...
2022-11-19 22:52:12.509Z: $ git -C "/var/lib/docker/codespacemount/workspace" clone --branch main --depth 1 https://github.com/grantmcdermott/codespaces-r2u "/var/lib/docker/codespacemount/workspace/codespaces-r2u"
2022-11-19 22:52:12.601Z: Cloning into '/var/lib/docker/codespacemount/workspace/codespaces-r2u'...
2022-11-19 22:52:15.814Z: git process exited with exit code 0
2022-11-19 22:52:15.818Z: $ git -C "/var/lib/docker/codespacemount/workspace/codespaces-r2u" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
2022-11-19 22:52:15.836Z: git process exited with exit code 0

=================================================================================
2022-11-19 22:52:16.503Z: Creating container...
2022-11-19 22:52:16.927Z: @microsoft/vscode-dev-containers-cli 0.74.2.
2022-11-19 22:52:16.955Z: Start: Resolving Remote
2022-11-19 22:52:16.955Z: $ docker ps -q -a --filter label=Type=codespaces
2022-11-19 22:52:17.012Z: Stop (56 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-11-19 22:52:17.012Z: $ /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/codespaces-r2u --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/codespaces-r2u/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-11-19 22:52:17.207Z: @devcontainers/cli 0.23.2. Node.js v14.20.1. linux 5.4.0-1094-azure x64.
2022-11-19 22:52:17.236Z: $ docker buildx version
2022-11-19 22:52:17.319Z: Stop (88 ms): Run: docker buildx version
2022-11-19 22:52:17.319Z: github.com/docker/buildx 0.9.1+azure-2 ed00243a0ce2a0aee75311b06e32d33b44729689
2022-11-19 22:52:17.319Z: 
2022-11-19 22:52:17.320Z: Start: Resolving Remote
2022-11-19 22:52:17.320Z: $ docker ps -q -a --filter label=Type=codespaces
2022-11-19 22:52:17.348Z: Stop (26 ms): Run: docker ps -q -a --filter label=Type=codespaces
2022-11-19 22:52:17.348Z: $ubuntu
2022-11-19 22:52:17.431Z: Stop (84 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:ubuntu
2022-11-19 22:52:17.431Z: local container features stored at: /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/node_modules/vscode-dev-containers/container-features
2022-11-19 22:52:17.431Z: $ tar --no-same-owner -x -f -
2022-11-19 22:52:17.459Z: Stop (37 ms): Run: tar --no-same-owner -x -f -
2022-11-19 22:52:17.487Z: * Processing feature: ghcr.io/rocker-org/devcontainer-features/r-apt:latest
2022-11-19 22:52:17.880Z: * Fetching feature: r-apt_1_oci
2022-11-19 22:52:18.385Z: $ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-codespaces-r2u-233a5a51aff712c1c09b3195267d30c9-features -f /tmp/devcontainercli-root/container-features/0.23.2-1668898337417/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2022-11-19 22:52:18.750Z: #1 [internal] load build definition from Dockerfile.extended
2022-11-19 22:52:18.751Z: 
2022-11-19 22:52:18.751Z: #1 transferring dockerfile: 2.52kB done
2022-11-19 22:52:18.751Z: #1 DONE 0.1s
2022-11-19 22:52:18.751Z: 
2022-11-19 22:52:18.751Z: #2 [internal] load .dockerignore
2022-11-19 22:52:18.751Z: #2 transferring context: 2B done
2022-11-19 22:52:18.918Z: #2 DONE 0.2s
2022-11-19 22:52:18.918Z: 
2022-11-19 22:52:18.918Z: #3 resolve image config for docker.io/docker/dockerfile:1.4
2022-11-19 22:52:19.199Z: #3 ...
2022-11-19 22:52:19.199Z: 
2022-11-19 22:52:19.199Z: #4 [auth] docker/dockerfile:pull token for registry-1.docker.io
2022-11-19 22:52:19.199Z: #4 DONE 0.0s
2022-11-19 22:52:19.363Z: 
2022-11-19 22:52:19.363Z: #3 resolve image config for docker.io/docker/dockerfile:1.4
2022-11-19 22:52:20.236Z: #3 DONE 1.3s
2022-11-19 22:52:20.236Z: 
2022-11-19 22:52:20.236Z: #5 docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc
2022-11-19 22:52:20.236Z: 
2022-11-19 22:52:20.236Z: #5 resolve docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc 0.1s done
2022-11-19 22:52:20.319Z: #5 sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc 2.00kB / 2.00kB done
2022-11-19 22:52:20.319Z: #5 sha256:ad87fb03593d1b71f9a1cfc1406c4aafcb253b1dabebf569768d6e6166836f34 528B / 528B done
2022-11-19 22:52:20.319Z: #5 sha256:1e8a16826fd1c80a63fa6817a9c7284c94e40cded14a9b0d0d3722356efa47bd 2.37kB / 2.37kB done
2022-11-19 22:52:20.319Z: #5 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0B / 9.94MB 0.1s
2022-11-19 22:52:20.575Z: #5 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 3.15MB / 9.94MB 0.3s
2022-11-19 22:52:20.757Z: #5 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.44MB / 9.94MB 0.5s
2022-11-19 22:52:20.886Z: #5 sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 9.94MB / 9.94MB 0.5s done
2022-11-19 22:52:20.886Z: #5 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546
2022-11-19 22:52:21.219Z: #5 extracting sha256:1328b32c40fca9bcf9d70d8eccb72eb873d1124d72dadce04db8badbe7b08546 0.2s done
2022-11-19 22:52:21.359Z: #5 DONE 1.2s
2022-11-19 22:52:21.360Z: 
2022-11-19 22:52:21.667Z: 
2022-11-19 22:52:21.667Z: #6 [internal] load .dockerignore
2022-11-19 22:52:21.667Z: #6 DONE 0.0s
2022-11-19 22:52:21.667Z: 
2022-11-19 22:52:21.667Z: #7 [internal] load build definition from Dockerfile.extended
2022-11-19 22:52:21.667Z: #7 DONE 0.0s
2022-11-19 22:52:21.808Z: 
2022-11-19 22:52:21.808Z: #8 [internal] load metadata for mcr.microsoft.com/devcontainers/base:ubuntu
2022-11-19 22:52:21.808Z: #8 DONE 0.0s
2022-11-19 22:52:21.808Z: 
2022-11-19 22:52:21.808Z: #9 [context dev_containers_feature_content_source] load .dockerignore
2022-11-19 22:52:21.808Z: #9 transferring dev_containers_feature_content_source: 2B done
2022-11-19 22:52:21.808Z: #9 DONE 0.1s
2022-11-19 22:52:22.119Z: 
2022-11-19 22:52:22.119Z: #10 [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.com/devcontainers/base:ubuntu
2022-11-19 22:52:22.704Z: #10 ...
2022-11-19 22:52:22.705Z: 
2022-11-19 22:52:22.705Z: #11 [context dev_containers_feature_content_source] load from client
2022-11-19 22:52:22.705Z: #11 transferring dev_containers_feature_content_source: 306.08kB done
2022-11-19 22:52:22.705Z: #11 DONE 0.5s
2022-11-19 22:52:22.846Z: 
2022-11-19 22:52:22.846Z: #10 [dev_containers_feature_content_normalize 1/3] FROM mcr.microsoft.com/devcontainers/base:ubuntu
2022-11-19 22:52:23.769Z: #10 DONE 1.6s
2022-11-19 22:52:23.769Z: 
2022-11-19 22:52:23.769Z: #12 [dev_containers_feature_content_normalize 2/3] COPY --from=dev_containers_feature_content_source . /tmp/build-features/
2022-11-19 22:52:24.053Z: #12 DONE 0.3s
2022-11-19 22:52:24.053Z: 
2022-11-19 22:52:24.053Z: 
2022-11-19 22:52:24.053Z: #13 [dev_containers_feature_content_normalize 3/3] RUN chmod -R 0700 /tmp/build-features
2022-11-19 22:52:24.053Z: 
2022-11-19 22:52:25.363Z: #13 DONE 1.4s
2022-11-19 22:52:25.531Z: 
2022-11-19 22:52:25.531Z: #14 [dev_containers_target_stage 2/4] COPY --from=dev_containers_feature_content_normalize /tmp/build-features /tmp/build-features
2022-11-19 22:52:25.812Z: #14 DONE 0.3s
2022-11-19 22:52:25.812Z: 
2022-11-19 22:52:25.812Z: #15 [dev_containers_target_stage 3/4] RUN echo "_CONTAINER_USER_HOME=$(getent passwd root | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env && echo "_REMOTE_USER_HOME=$(getent passwd vscode | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env
2022-11-19 22:52:26.429Z: #15 DONE 0.6s
2022-11-19 22:52:26.429Z: 
2022-11-19 22:52:26.430Z: #16 [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/r-apt_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh
2022-11-19 22:52:26.842Z: #16 0.477 ===========================================================================
2022-11-19 22:52:26.843Z: #16 0.477 Feature       : R (via apt)
2022-11-19 22:52:26.843Z: #16 0.477 Description   : Installs the latest R, some R packages, and needed dependencies. Note: May require source code compilation for some R packages.
2022-11-19 22:52:26.843Z: #16 0.477 Id            : ghcr.io/rocker-org/devcontainer-features/r-apt
2022-11-19 22:52:26.843Z: #16 0.477 Version       : 0.2.0
2022-11-19 22:52:26.843Z: #16 0.477 Documentation : https://github.com/rocker-org/devcontainer-features/tree/main/src/r-apt
2022-11-19 22:52:26.843Z: #16 0.477 Options       :
2022-11-19 22:52:26.843Z: #16 0.477     VSCODERSUPPORT="full"
2022-11-19 22:52:26.843Z: #16 0.477     INSTALLDEVTOOLS="false"
2022-11-19 22:52:26.843Z: #16 0.477     INSTALLRMARKDOWN="false"
2022-11-19 22:52:26.843Z: #16 0.477     INSTALLJUPYTERLAB="false"
2022-11-19 22:52:26.843Z: #16 0.477     INSTALLRADIAN="true"
2022-11-19 22:52:26.843Z: #16 0.477     INSTALLVSCDEBUGGER="false"
2022-11-19 22:52:26.843Z: #16 0.477     USETESTING="true"
2022-11-19 22:52:26.843Z: #16 0.477 ===========================================================================
2022-11-19 22:52:27.087Z: #16 0.748 Set up for Ubuntu...
2022-11-19 22:52:27.843Z: #16 1.402 Set up r2u...
2022-11-19 22:52:28.465Z: #16 1.969 Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3626 B]
2022-11-19 22:52:28.468Z: 
2022-11-19 22:52:28.468Z: #16 1.988 Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
2022-11-19 22:52:28.468Z: #16 2.050 Get:3 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
2022-11-19 22:52:28.579Z: #16 2.238 Ign:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
2022-11-19 22:52:28.692Z: #16 2.270 Get:5 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [26.3 kB]
2022-11-19 22:52:28.692Z: #16 2.293 Get:6 https://r2u.stat.illinois.edu/ubuntu jammy Release [5713 B]
2022-11-19 22:52:28.692Z: #16 2.347 Get:7 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]
2022-11-19 22:52:28.804Z: #16 2.460 Get:8 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [767 kB]
2022-11-19 22:52:28.916Z: #16 2.482 Get:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
2022-11-19 22:52:28.916Z: #16 2.569 Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2177 kB]
2022-11-19 22:52:29.028Z: #16 2.569 Err:10 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages
2022-11-19 22:52:29.028Z: 
2022-11-19 22:52:29.028Z: #16 2.569   File has unexpected size (2176570 != 2176824). Mirror sync in progress? [IP: 192.17.190.167 443]
2022-11-19 22:52:29.028Z: #16 2.569   Hashes of expected file:
2022-11-19 22:52:29.028Z: #16 2.569    - Filesize:2176824 [weak]
2022-11-19 22:52:29.028Z: #16 2.569    - SHA512:be9e4cf225ba74547f526ddd0165e80d0be3528c59b07197dbeb63041f8d3c3e9eb264de9adc2b894b7a5568ab17df0c2c21de2c41ee6bd5637981894841da62
2022-11-19 22:52:29.028Z: #16 2.569    - SHA256:878639be5347ac979da080fddef0496c8c83669c4e23051b03bc27861e5e991b
2022-11-19 22:52:29.028Z: #16 2.569    - SHA1:c69a20462f55cf18f1ffccee0762e1a7254571f7 [weak]
2022-11-19 22:52:29.028Z: #16 2.569    - MD5Sum:49fad20a987e7dacdfde67ef8bcc46f8 [weak]
2022-11-19 22:52:29.028Z: #16 2.569   Release file created at: Sat, 19 Nov 2022 19:44:12 +0000
2022-11-19 22:52:29.028Z: #16 2.583 Get:11 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
2022-11-19 22:52:29.028Z: #16 2.684 Get:12 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
2022-11-19 22:52:29.168Z: #16 2.722 Get:13 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
2022-11-19 22:52:29.169Z: #16 2.775 Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
2022-11-19 22:52:29.169Z: #16 2.808 Get:15 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4642 B]
2022-11-19 22:52:29.308Z: #16 2.810 Get:16 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [614 kB]
2022-11-19 22:52:29.308Z: #16 2.853 Get:17 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [522 kB]
2022-11-19 22:52:29.308Z: #16 2.886 Get:18 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [6759 kB]
2022-11-19 22:52:29.311Z: #16 2.887 Err:18 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages
2022-11-19 22:52:29.311Z: #16 2.888   
2022-11-19 22:52:29.311Z: #16 2.949 Get:19 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
2022-11-19 22:52:29.887Z: #16 3.468 Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [573 kB]
2022-11-19 22:52:29.887Z: #16 3.478 Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [8056 B]
2022-11-19 22:52:29.888Z: #16 3.479 Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [952 kB]
2022-11-19 22:52:29.888Z: #16 3.494 Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [914 kB]
2022-11-19 22:52:29.889Z: #16 3.517 Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [3175 B]
2022-11-19 22:52:30.034Z: #16 3.518 Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [7275 B]
2022-11-19 22:52:30.928Z: #16 4.480 Fetched 24.7 MB in 3s (9281 kB/s)
2022-11-19 22:52:30.928Z: #16 4.480 Reading package lists...
2022-11-19 22:52:31.487Z: 
2022-11-19 22:52:31.488Z: #16 5.129 E: Failed to fetch https://r2u.stat.illinois.edu/ubuntu/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (2176570 != 2176824). Mirror sync in progress? [IP: 192.17.190.167 443]
2022-11-19 22:52:31.488Z: #16 5.129    Hashes of expected file:
2022-11-19 22:52:31.488Z: #16 5.129     - Filesize:2176824 [weak]
2022-11-19 22:52:31.490Z: #16 5.129     - SHA512:be9e4cf225ba74547f526ddd0165e80d0be3528c59b07197dbeb63041f8d3c3e9eb264de9adc2b894b7a5568ab17df0c2c21de2c41ee6bd5637981894841da62
2022-11-19 22:52:31.491Z: #16 5.129     - SHA256:878639be5347ac979da080fddef0496c8c83669c4e23051b03bc27861e5e991b
2022-11-19 22:52:31.491Z: #16 5.129     - SHA1:c69a20462f55cf18f1ffccee0762e1a7254571f7 [weak]
2022-11-19 22:52:31.491Z: #16 5.129     - MD5Sum:49fad20a987e7dacdfde67ef8bcc46f8 [weak]
2022-11-19 22:52:31.492Z: #16 5.129    Release file created at: Sat, 19 Nov 2022 19:44:12 +0000
2022-11-19 22:52:31.492Z: #16 5.129 E
2022-11-19 22:52:31.636Z: : Failed to fetch https://r2u.stat.illinois.edu/ubuntu/dists/jammy/main/binary-all/Packages.gz  
2022-11-19 22:52:31.636Z: #16 5.129 E: Some index files failed to download. They have been ignored, or old ones used instead.
2022-11-19 22:52:31.636Z: #16 5.131 ERROR: Feature "R (via apt)" (ghcr.io/rocker-org/devcontainer-features/r-apt) failed to install! Look at the documentation at https://github.com/rocker-org/devcontainer-features/tree/main/src/r-apt for help troubleshooting this error.
2022-11-19 22:52:31.833Z: #16 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/r-apt_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 100
2022-11-19 22:52:31.833Z: ------
2022-11-19 22:52:31.833Z:  > [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/r-apt_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
2022-11-19 22:52:31.833Z: #16 2.949 Get:19 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
2022-11-19 22:52:31.833Z: #16 3.468 Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [573 kB]
2022-11-19 22:52:31.833Z: #16 3.478 Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [8056 B]
2022-11-19 22:52:31.833Z: #16 3.479 Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [952 kB]
2022-11-19 22:52:31.833Z: #16 3.494 Get:23 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [914 kB]
2022-11-19 22:52:31.833Z: #16 3.517 Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [3175 B]
2022-11-19 22:52:31.833Z: #16 3.518 Get:25 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [7275 B]
2022-11-19 22:52:31.833Z: : Failed to fetch https://r2u.stat.illinois.edu/ubuntu/dists/jammy/main/binary-all/Packages.gz  
2022-11-19 22:52:31.833Z: #16 5.129 E: Some index files failed to download. They have been ignored, or old ones used instead.
2022-11-19 22:52:31.833Z: #16 5.131 ERROR: Feature "R (via apt)" (ghcr.io/rocker-org/devcontainer-features/r-apt) failed to install! Look at the documentation at https://github.com/rocker-org/devcontainer-features/tree/main/src/r-apt for help troubleshooting this error.
2022-11-19 22:52:31.833Z: ------
2022-11-19 22:52:31.833Z: ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/r-apt_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 100
2022-11-19 22:52:31.861Z: Stop (13469 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.23.2-1668898337417 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-codespaces-r2u-233a5a51aff712c1c09b3195267d30c9-features -f /tmp/devcontainercli-root/container-features/0.23.2-1668898337417/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2022-11-19 22:52:31.861Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.23.2-1668898337417 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-codespaces-r2u-233a5a51aff712c1c09b3195267d30c9-features -f /tmp/devcontainercli-root/container-features/0.23.2-1668898337417/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2022-11-19 22:52:31.861Z:     at loe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1887:1339)
2022-11-19 22:52:31.861Z:     at eT (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1887:1275)
2022-11-19 22:52:31.861Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-11-19 22:52:31.861Z:     at async voe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1893:2049)
2022-11-19 22:52:31.861Z:     at async Xf (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1893:3212)
2022-11-19 22:52:31.861Z:     at async Jae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2013:15058)
2022-11-19 22:52:31.861Z:     at async Wae (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2013:14812)
2022-11-19 22:52:31.862Z: Stop (14873 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/codespaces-r2u --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/codespaces-r2u/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-11-19 22:52:31.862Z: Exit code 1

====================================== ERROR ====================================
2022-11-19 22:52:31.891Z: Failed to create container.
=================================================================================
2022-11-19 22:52:31.895Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/codespaces-r2u --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/codespaces-r2u/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-11-19 22:52:31.896Z: Error Code: 1302

====================================== ERROR ====================================
2022-11-19 22:52:31.914Z: Container creation failed.
=================================================================================
2022-11-19 22:52:31.939Z: 

===================================== WARNING ===================================
2022-11-19 22:52:31.940Z: Creating recovery container.
=================================================================================

=================================================================================
2022-11-19 22:53:19.313Z: Creating container...

=================================================================================
2022-11-19 22:53:28.323Z: Running blocking commands...

=================================================================================
2022-11-19 22:53:30.240Z: Configuring codespace...

=================================================================================
2022-11-19 22:53:30.350Z: Finished configuring codespace.

</details>

**Comment by cboettig** [comment]
The other devs have more expertise on r-apt but this looks to me like a chance/stochastic network error (i.e. files being updated on the mirror at precisely the time you are trying to pull them), so maybe try again in a bit?

**Comment by eddelbuettel** [comment]
Yes, that looks like effed-up indices.  Over all these years I have seen this every now and then.  I think the best (only?) recourse I could come with was to blow out the _local_ apt indices forcing download of new ones after which it improves. So try blowing out `/var/lib/apt/lists/` (or, more savely, rename to `listsHIDDEN` ).

(I was rebuilding all day for `r2u` but that should not have impacted anything as I was careful when/how to `rsync` out, and I re-used my own builds too.  We're now current with BioConductor 3.16 for the 240-ish BioC packages we have.)

(Also: wrong repo but not sure where @eitsupi keeps the code for these new devcontainers so maybe he can / should transfer the issue.)

**Comment by grantmcdermott** [comment]
Thanks both. Agree that borked indices seems the likely issue. I just tested on my local machine and ran into the same problem.

> (Also: wrong repo but not sure where @eitsupi keeps the code for these new devcontainers so maybe he can / should transfer the issue.)

Ugh, sorry. Should have filed under [rocker-org/devcontainer-features](https://github.com/rocker-org/devcontainer-features). I'll wait for eitsupi to transfer.

**Comment by eddelbuettel** [comment]
If you are daring, try blowing away the indices. And/or mock up a fresh setting by doing it inside a Docker container.
